In [2]:
import pandas as pd
print(pd.__version__)

2.3.0

In [3]:
df = pd.read_csv("insta.csv")
print(df.head(5))

      Username Channel Name Country Main video category         Likes  \
0    cristiano    cristiano      ES              Sports  2.287645e+10
1  kyliejenner  kyliejenner      US                 NaN  4.304855e+10
2     leomessi     leomessi     NaN                 NaN  4.670492e+09
3  selenagomez  selenagomez      US                 NaN  8.442643e+09
4      therock      therock      US                 NaN  9.562231e+09

    Likes Avg.  Posts  Followers  Boost Index  Comments Avg.    Views Avg.  \
0  8671952.688   3328  465027234           92   51758.330930  1.700949e+07
1  8296735.663   6921  356687629           91   47534.120960  2.287547e+07
2  6895177.813    875  347032978           90   47044.540310  1.176160e+07
3  6252711.417   1835  334551681           93   39167.115730  1.072397e+07
4  1874150.504   6660  327064138           91    8529.747043  5.413831e+06

   Avg. 1 Day  Avg. 3 Day  Avg. 7 Day  Avg. 14 Day  Avg. 30 Day  \
0         NaN         NaN   3321113.0  5327340.250  6948658.867
1         NaN         NaN   1223002.0  2196528.500  4692458.947
2         NaN   4810554.0   3199807.0  5359468.600  5668453.857
3         NaN         NaN         NaN  2340219.000  2340219.000
4         NaN         NaN    713970.0  1101338.556  1165227.385

   Engagement Rate  Engagement Rate (60 Days)
0         0.014916                   0.015903
1         0.017617                   0.016189
2         0.015534                   0.019045
3         0.013913                   0.007720
4         0.004426                   0.003723

In [4]:
print(df.columns)

Index(['Username', 'Channel Name', 'Country', 'Main video category', 'Likes',
       'Likes Avg.', 'Posts', 'Followers', 'Boost Index', 'Comments Avg.',
       'Views Avg.', 'Avg. 1 Day', 'Avg. 3 Day', 'Avg. 7 Day', 'Avg. 14 Day',
       'Avg. 30 Day', 'Engagement Rate', 'Engagement Rate (60 Days)'],
      dtype='object')

In [5]:
df.info()

df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Username                   200 non-null    object
 1   Channel Name               200 non-null    object
 2   Country                    138 non-null    object
 3   Main video category        133 non-null    object
 4   Likes                      200 non-null    float64
 5   Likes Avg.                 200 non-null    float64
 6   Posts                      200 non-null    int64
 7   Followers                  200 non-null    int64
 8   Boost Index                200 non-null    int64
 9   Comments Avg.              200 non-null    float64
 10  Views Avg.                 197 non-null    float64
 11  Avg. 1 Day                 61 non-null     float64
 12  Avg. 3 Day                 125 non-null    float64
 13  Avg. 7 Day                 162 non-null    float64
 14  Avg. 14 Day                186 non-null    float64
 15  Avg. 30 Day                195 non-null    float64
 16  Engagement Rate            200 non-null    float64
 17  Engagement Rate (60 Days)  200 non-null    float64
dtypes: float64(11), int64(3), object(4)
memory usage: 28.3+ KB

(200, 18)

In [6]:
df.describe ()

,Likes,Likes Avg.,Posts,Followers,Boost Index,Comments Avg.,Views Avg.,Avg. 1 Day,Avg. 3 Day,Avg. 7 Day,Avg. 14 Day,Avg. 30 Day,Engagement Rate,Engagement Rate (60 Days)
count,2.000000e+02,2.000000e+02,200.000000,2.000000e+02,200.000000,200.000000,1.970000e+02,6.100000e+01,1.250000e+02,1.620000e+02,1.860000e+02,1.950000e+02,200.000000,2.000000e+02
mean,2.872531e+09,1.794036e+06,3894.685000,7.624449e+07,81.835000,9657.213702,4.122729e+06,2.201832e+05,6.969034e+05,1.078521e+06,1.180878e+06,1.243577e+06,0.023890,2.144167e-02
std,4.270441e+09,2.196261e+06,7554.327506,7.183988e+07,8.877603,12881.941966,4.000589e+06,4.167407e+05,1.201042e+06,1.871746e+06,1.915094e+06,1.919040e+06,0.040163,3.681096e-02
min,1.009315e+07,6.724715e+04,16.000000,3.281203e+07,22.000000,0.176471,3.581595e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.001092,4.970000e-09
25%,8.314277e+08,5.155011e+05,931.750000,3.956486e+07,80.000000,2533.300093,1.499868e+06,2.826400e+04,6.848800e+04,1.259690e+05,1.562158e+05,2.105310e+05,0.007584,4.442543e-03
50%,1.668507e+09,1.120528e+06,2084.500000,4.973707e+07,84.000000,5344.109683,2.896416e+06,8.393733e+04,2.302396e+05,3.748735e+05,4.515066e+05,5.394430e+05,0.014105,1.031813e-02
75%,3.225456e+09,2.106021e+06,4990.250000,6.814704e+07,86.000000,10124.004020,5.690915e+06,2.160880e+05,8.141800e+05,1.054254e+06,1.143059e+06,1.422887e+06,0.024342,2.192624e-02
max,4.304855e+10,1.553868e+07,99022.000000,4.650272e+08,93.000000,69133.050000,2.478636e+07,2.888035e+06,6.702150e+06,1.300787e+07,1.314321e+07,1.321100e+07,0.345696,2.987771e-01

In [7]:
df.isnull().sum()

Username                       0
Channel Name                   0
Country                       62
Main video category           67
Likes                          0
Likes Avg.                     0
Posts                          0
Followers                      0
Boost Index                    0
Comments Avg.                  0
Views Avg.                     3
Avg. 1 Day                   139
Avg. 3 Day                    75
Avg. 7 Day                    38
Avg. 14 Day                   14
Avg. 30 Day                    5
Engagement Rate                0
Engagement Rate (60 Days)      0
dtype: int64

In [8]:
df["Likes"]

0      2.287645e+10
1      4.304855e+10
2      4.670492e+09
3      8.442643e+09
4      9.562231e+09
           ...
195    1.121343e+08
196    2.355851e+09
197    1.364537e+09
198    1.039639e+09
199    1.033749e+09
Name: Likes, Length: 200, dtype: float64

In [9]:
df["Engagement Rate"]

0      0.014916
1      0.017617
2      0.015534
3      0.013913
4      0.004426
         ...
195    0.005050
196    0.053036
197    0.017990
198    0.015257
199    0.014031
Name: Engagement Rate, Length: 200, dtype: float64

In [10]:
df['Engagement'] = df['Likes'] + df['Followers']

In [11]:
df['Engagement']

0      2.334148e+10
1      4.340523e+10
2      5.017525e+09
3      8.777194e+09
4      9.889295e+09
           ...
195    1.451588e+08
196    2.388790e+09
197    1.397444e+09
198    1.072485e+09
199    1.066561e+09
Name: Engagement, Length: 200, dtype: float64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Username                   200 non-null    object
 1   Channel Name               200 non-null    object
 2   Country                    138 non-null    object
 3   Main video category        133 non-null    object
 4   Likes                      200 non-null    float64
 5   Likes Avg.                 200 non-null    float64
 6   Posts                      200 non-null    int64
 7   Followers                  200 non-null    int64
 8   Boost Index                200 non-null    int64
 9   Comments Avg.              200 non-null    float64
 10  Views Avg.                 197 non-null    float64
 11  Avg. 1 Day                 61 non-null     float64
 12  Avg. 3 Day                 125 non-null    float64
 13  Avg. 7 Day                 162 non-null    float64
 14  Avg. 14 Day                186 non-null    float64
 15  Avg. 30 Day                195 non-null    float64
 16  Engagement Rate            200 non-null    float64
 17  Engagement Rate (60 Days)  200 non-null    float64
 18  Engagement                 200 non-null    float64
dtypes: float64(12), int64(3), object(4)
memory usage: 29.8+ KB

In [13]:
df.drop('Engagement Rate (60 Days)', axis=1)

,Username,Channel Name,Country,Main video category,Likes,Likes Avg.,Posts,Followers,Boost Index,Comments Avg.,Views Avg.,Avg. 1 Day,Avg. 3 Day,Avg. 7 Day,Avg. 14 Day,Avg. 30 Day,Engagement Rate,Engagement
0,cristiano,cristiano,ES,Sports,2.287645e+10,8.671953e+06,3328,465027234,92,51758.330930,1.700949e+07,NaN,NaN,3.321113e+06,5.327340e+06,6.948659e+06,0.014916,2.334148e+10
1,kyliejenner,kyliejenner,US,NaN,4.304855e+10,8.296736e+06,6921,356687629,91,47534.120960,2.287547e+07,NaN,NaN,1.223002e+06,2.196528e+06,4.692459e+06,0.017617,4.340523e+10
2,leomessi,leomessi,NaN,NaN,4.670492e+09,6.895178e+06,875,347032978,90,47044.540310,1.176160e+07,NaN,4.810554e+06,3.199807e+06,5.359469e+06,5.668454e+06,0.015534,5.017525e+09
3,selenagomez,selenagomez,US,NaN,8.442643e+09,6.252711e+06,1835,334551681,93,39167.115730,1.072397e+07,NaN,NaN,NaN,2.340219e+06,2.340219e+06,0.013913,8.777194e+09
4,therock,therock,US,NaN,9.562231e+09,1.874151e+06,6660,327064138,91,8529.747043,5.413831e+06,NaN,NaN,7.139700e+05,1.101339e+06,1.165227e+06,0.004426,9.889295e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,luansantana,luansantana,BR,NaN,1.121343e+08,2.055880e+05,714,33024460,79,4795.100970,5.287625e+05,NaN,2.110623e+05,1.293861e+05,1.938759e+05,1.824987e+05,0.005050,1.451588e+08
196,danbilzerian,danbilzerian,CA,Pets & Animals,2.355851e+09,2.044189e+06,1372,32938902,84,24680.813190,2.103653e+07,NaN,1.079742e+06,1.079742e+06,1.079742e+06,1.079742e+06,0.053036,2.388790e+09
197,nickjonas,nickjonas,US,NaN,1.364537e+09,7.442257e+05,2315,32906383,78,2191.083551,1.089024e+06,NaN,6.552600e+04,6.552600e+04,6.552600e+04,3.396173e+05,0.017990,1.397444e+09
198,gururandhawa,gururandhawa,US,Education,1.039639e+09,6.377582e+05,2140,32845959,83,3837.251476,2.267251e+06,NaN,2.182120e+05,2.324327e+05,3.073671e+05,2.898926e+05,0.015257,1.072485e+09
199,iambeckyg,iambeckyg,US,NaN,1.033749e+09,6.254215e+05,2270,32812027,71,1588.418605,1.020376e+06,NaN,2.329310e+05,3.001740e+05,3.218177e+05,3.962579e+05,0.014031,1.066561e+09

In [14]:
df.drop(["Avg. 3 Day","Main video category","Boost Index","Username","Avg. 1 Day","Likes","Engagement Rate (60 Days)"], axis=1, inplace=True)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Channel Name     200 non-null    object
 1   Country          138 non-null    object
 2   Likes Avg.       200 non-null    float64
 3   Posts            200 non-null    int64
 4   Followers        200 non-null    int64
 5   Comments Avg.    200 non-null    float64
 6   Views Avg.       197 non-null    float64
 7   Avg. 7 Day       162 non-null    float64
 8   Avg. 14 Day      186 non-null    float64
 9   Avg. 30 Day      195 non-null    float64
 10  Engagement Rate  200 non-null    float64
 11  Engagement       200 non-null    float64
dtypes: float64(8), int64(2), object(2)
memory usage: 18.9+ KB

In [16]:
df.fillna({'Views Avg.': 0.0}, inplace=True)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Channel Name     200 non-null    object
 1   Country          138 non-null    object
 2   Likes Avg.       200 non-null    float64
 3   Posts            200 non-null    int64
 4   Followers        200 non-null    int64
 5   Comments Avg.    200 non-null    float64
 6   Views Avg.       200 non-null    float64
 7   Avg. 7 Day       162 non-null    float64
 8   Avg. 14 Day      186 non-null    float64
 9   Avg. 30 Day      195 non-null    float64
 10  Engagement Rate  200 non-null    float64
 11  Engagement       200 non-null    float64
dtypes: float64(8), int64(2), object(2)
memory usage: 18.9+ KB

In [18]:
df.fillna({'Avg. 7 Day':0, 'Avg. 14 Day':0,'Avg. 30 Day':0 }, inplace=True)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Channel Name     200 non-null    object
 1   Country          138 non-null    object
 2   Likes Avg.       200 non-null    float64
 3   Posts            200 non-null    int64
 4   Followers        200 non-null    int64
 5   Comments Avg.    200 non-null    float64
 6   Views Avg.       200 non-null    float64
 7   Avg. 7 Day       200 non-null    float64
 8   Avg. 14 Day      200 non-null    float64
 9   Avg. 30 Day      200 non-null    float64
 10  Engagement Rate  200 non-null    float64
 11  Engagement       200 non-null    float64
dtypes: float64(8), int64(2), object(2)
memory usage: 18.9+ KB

In [20]:
df['Country'] = df['Country'].fillna('Unknown')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Channel Name     200 non-null    object
 1   Country          200 non-null    object
 2   Likes Avg.       200 non-null    float64
 3   Posts            200 non-null    int64
 4   Followers        200 non-null    int64
 5   Comments Avg.    200 non-null    float64
 6   Views Avg.       200 non-null    float64
 7   Avg. 7 Day       200 non-null    float64
 8   Avg. 14 Day      200 non-null    float64
 9   Avg. 30 Day      200 non-null    float64
 10  Engagement Rate  200 non-null    float64
 11  Engagement       200 non-null    float64
dtypes: float64(8), int64(2), object(2)
memory usage: 18.9+ KB

In [23]:
df['Engagement per Follower'] = df['Engagement'] / df['Followers']
df['Likes per Post'] = df['Likes Avg.'] / df['Posts']

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Channel Name             200 non-null    object
 1   Country                  200 non-null    object
 2   Likes Avg.               200 non-null    float64
 3   Posts                    200 non-null    int64
 4   Followers                200 non-null    int64
 5   Comments Avg.            200 non-null    float64
 6   Views Avg.               200 non-null    float64
 7   Avg. 7 Day               200 non-null    float64
 8   Avg. 14 Day              200 non-null    float64
 9   Avg. 30 Day              200 non-null    float64
 10  Engagement Rate          200 non-null    float64
 11  Engagement               200 non-null    float64
 12  Engagement per Follower  200 non-null    float64
 13  Likes per Post           200 non-null    float64
dtypes: float64(10), int64(2), object(2)
memory usage: 22.0+ KB

In [33]:
import pandas as pd

# Load CSV files
df_main = pd.read_csv('instagram_cleaned.csv')
df_extra = pd.read_csv('insta.csv')

# Merge category column into main data
df_merged = df_main.merge(
    df_extra[['Channel Name', 'Main video category']],  # must be DataFrame
    on='Channel Name',                                  # common column
    how='left'
)

# Save final CSV
df_merged.to_csv('final_instagram_data.csv', index=False)

In [36]:
df = pd.read_csv('final_instagram_data.csv')
df['Main video category'] = df['Main video category'].fillna('Unknown')

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Channel Name             200 non-null    object
 1   Country                  200 non-null    object
 2   Likes Avg.               200 non-null    float64
 3   Posts                    200 non-null    int64
 4   Followers                200 non-null    int64
 5   Comments Avg.            200 non-null    float64
 6   Views Avg.               200 non-null    float64
 7   Avg. 7 Day               200 non-null    float64
 8   Avg. 14 Day              200 non-null    float64
 9   Avg. 30 Day              200 non-null    float64
 10  Engagement Rate          200 non-null    float64
 11  Engagement               200 non-null    float64
 12  Engagement per Follower  200 non-null    float64
 13  Likes per Post           200 non-null    float64
 14  Main video category      200 non-null    object
dtypes: float64(10), int64(2), object(3)
memory usage: 23.6+ KB

In [38]:
df.head()

,Channel Name,Country,Likes Avg.,Posts,Followers,Comments Avg.,Views Avg.,Avg. 7 Day,Avg. 14 Day,Avg. 30 Day,Engagement Rate,Engagement,Engagement per Follower,Likes per Post,Main video category
0,cristiano,ES,8671952.688,3328,465027234,51758.330930,1.700949e+07,3321113.0,5327340.250,6948658.867,0.014916,2.334148e+10,50.193789,2605.755014,Sports
1,kyliejenner,US,8296735.663,6921,356687629,47534.120960,2.287547e+07,1223002.0,2196528.500,4692458.947,0.017617,4.340523e+10,121.689762,1198.777007,Unknown
2,leomessi,Unknown,6895177.813,875,347032978,47044.540310,1.176160e+07,3199807.0,5359468.600,5668453.857,0.015534,5.017525e+09,14.458353,7880.203215,Unknown
3,selenagomez,US,6252711.417,1835,334551681,39167.115730,1.072397e+07,0.0,2340219.000,2340219.000,0.013913,8.777194e+09,26.235690,3407.472162,Unknown
4,therock,US,1874150.504,6660,327064138,8529.747043,5.413831e+06,713970.0,1101338.556,1165227.385,0.004426,9.889295e+09,30.236563,281.403980,Unknown

In [39]:
df.to_csv('final_instagram_data.csv', index=False)